language: node_js

node_js:
  - "6"

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y blender

script:
  - npm run test:cov

after_success:
  - npm install codecov
  - $(npm bin)/codecov
